name:                aoc18-hs
version:             0.1.0.0
github:              "plorefice/aoc18-hs"
license:             BSD3
author:              "Pietro Lorefice"
maintainer:          "pietro.lorefice@gmail.com"
copyright:           "2018 Pietro Lorefice"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/plorefice/aoc18-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- split
- dates

library:
  source-dirs: src

executables:
  task1:
    main:                Main.hs
    source-dirs:         task1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc18-hs

  task2:
    main:                Main.hs
    source-dirs:         task2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc18-hs

  task3:
    main:                Main.hs
    source-dirs:         task3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc18-hs

  task4:
    main:                Main.hs
    source-dirs:         task4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc18-hs

  task5:
    main:                Main.hs
    source-dirs:         task5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc18-hs